#!/usr/bin/env bash
# Install and Configure HAproxy on lb-01.
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo 'ENABLED=1' |sudo tee -a /etc/default/haproxy
sudo echo "
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 1627-web-01 35.243.146.56:80 check
    server 1627-web-02 34.73.2.194:80 check
"    | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart 
