#!/usr/bin/env bash
#process and pid file

sudo bash -c "echo N $$ > var/run/codingschoolscript.pid"
trap "sudo rm -f /var/run/codingschoolscript.pid; echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "sudo rm -f /var/run/codingschoolscript.pid; exit" SIGQUIT
while :
do
    echo "To infinity and beyond"
    sleep 2
done