#!/usr/bin/env bash

start() {
    sudo ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
}

stop() {
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    sudo rm /var/run/my_process.pid
}

restart() {
    kill "$(cat /var/run/my_process.pid)"
    sudo rm /var/run/my_process.pid
    sudo ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo manage_my_process restarted
}

case "$1" in
    start) start ;;
    stop)  stop;;
    restart) restart;;
    *) echo "Usage: manage_my_process {start|stop|restart}" > &2
        exit 1
        ;;
esac