#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i=1;
x=2;

while [ $i -le 12 ]
do
    echo Hour: $i
    x=1;
    while [ $x -le 59 ]
    do
        echo $x
        ((x++))
    done
    ((i++))
done